### PR TITLE
Block synchronous lock operations

### LINKED ISSUE #544: BlockingDistributedLock throws 100% of the time in some scenarios
On my laptop, I can reproduce the error below by doing the follow - I’m using the latest 2.1.0-SNAPSHOT version

1. Start atomix with 4 PERSISTENT nodes as follows...
```java
        final Atomix atomix = Atomix.builder()
                .withManagementGroup((RaftPartitionGroup.builder("system")
                        .withNumPartitions(1)
                        .withMembers(members.stream().toArray(Member[]::new))
                        .withDataDirectory(dataDir)
                        .build()))
                .withPartitionGroups(RaftPartitionGroup.builder("raft")
                        .withNumPartitions(1)
                        .withMembers(members.stream().toArray(Member[]::new))
                        .withDataDirectory(dataDir)
                        .build())
                .withMembers(members.stream().toArray(Member[]::new))
                .withLocalMember(local)
                .withClusterName("Cluster name")
                .build()
```

2. Take 1 node down
3. Take 1 more node down (now we have 2 nodes ups out of 4)
4. Start one of the previously downed nodes
5. Any node attempting to take a lock will get the following exception

```
io.atomix.primitive.PrimitiveException$Timeout: null
        at io.atomix.core.lock.impl.BlockingDistributedLock.complete(BlockingDistributedLock.java:77)
        at io.atomix.core.lock.impl.BlockingDistributedLock.tryLock(BlockingDistributedLock.java:57)
        at com.example.runOneIteration(xScheduler.java:55)
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by kuujo**
This PR fixes #544: synchronous lock operations should be blocked, and the underlying proxy should be responsible for timing out lock attempts. Otherwise, a lock can be acquired after the attempt is timed out and may never be released.

### CODE REVIEW

File: core/src/test/java/io/atomix/core/TestTest.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package io.atomix.core;
+
+/**
+ *
+ */
+public class TestTest {
```
Comment (johnou) [inline core/src/test/java/io/atomix/core/TestTest.java]: o yes!

Comment (kuujo) [reply core/src/test/java/io/atomix/core/TestTest.java]: Ugh

Comment (kuujo) [reply core/src/test/java/io/atomix/core/TestTest.java]: I'm actually not entirely sure how this got here. I did have a `TestTest` class, but it was a copy of the test from the related issue 🤷‍♂️
